"Changes: Audio":
  - changed-files:
    - any-glob-to-any-file:
        -  "**/*.ogg"
        - "**/*.mp3"
        - "**/*.wav"

"Changes: C/C++":
  - changed-files:
    - any-glob-to-any-file:
        - "**/*.c"
        - "**/*.cpp"
        - "**/*.ino"

"Changes: CAD Files":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.3mf"
      - "**/*.step"
      - "**/*.STEP"
      - "**/*.stl"
      - "**/*.STL"

"Changes: Headers":
  - changed-files:
    -  any-glob-to-any-file: "**/*.h"

"Changes: Config":
- changed-files:
  - any-glob-to-any-file:
    - "**/*.toml"
    - "**/*.config"
    - "*.json"
    - ".github/*.yml"
    - ".github/*.json"
    - ".vscode/*.json"
    - ".editorconfig"

"Changes: Documentation":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.txt"
      - "**/*.md"
      - "**/*.pdf"

"Changes: Images":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.svg"
      - "**/*.webp"

"Changes: PCB Files":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.kicad_mod"
      - "**/*.kicad_pcb"
      - "**/*.kicad_prl"
      - "**/*.kicad_pro"
      - "**/*.kicad_sch"
      - "**/*.kicad_sch-bak"
      - "**/*.kicad_sym"
      - "**/*.btm"
      - "**/*.drl"
      - "**/*.gbr"
      - "**/*.gbrjob"

"Changes: Workflow":
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/*.yml"
